### ISSUE TITLE
Error 1233 Expected a reference to an existing File/Folder

### ISSUE THREAD

**Issue by netcosi** [chilli-axe/mtg-photoshop-automation#31]
Hello! Sorry if this has been asked before, but I am encountering this issue if I try to render planeswalkers or saga cards. These scripts work amazing for any other card type, but if you could direct me to a fix this would be incredible. Thanks!

Error 1233: Expected a reference to an existing File/Folder 

Line: 389
-> app.load(file) 

It seems to be coming from the paste_file() function in helpers.jsx

**Comment by ndepaola** [comment]
this commit https://github.com/chilli-axe/mtg-photoshop-automation/commit/1d2890c3b2b604110c3b4862ae10c42117e6c408 means you only need to change the python system call in one place now, so hopefully this issue won't happen for people as much going forward :)
