### ISSUE TITLE
Error occurs when generating planeswalker cards

### ISSUE THREAD

**Issue by gauvingingras** [chilli-axe/mtg-photoshop-automation#33]
The following error always occurs when trying to generate a planeswalker card:

![image](https://user-images.githubusercontent.com/64083676/140647059-90bf7f94-f582-4d5b-8490-5b279ed2a72a.png)

The art is not a problem, as I can use the same art, give it the name of a creature and the card generates perfectly.

**Comment by ndepaola** [comment]
as per the readme, the system intentionally does this so you can manually adjust text placement. same thing happens with sagas.
